/* ===== Malaysia Trip — 单一数据源（第五轮：3晚MOV+1晚Port Dickson） ===== */
const TRIP = {
  meta: {
    title: 'Malaysia Trip',
    subtitle: '马来西亚五天四夜',
    dates: '2026.10.02 – 2026.10.06',
    travelers: 2,
    durationDays: 5,
    durationNights: 4,
    originCity: '杭州',
    destinationCity: 'Kuala Lumpur',
    heroImage: 'img/hero.webp',
    heroImageCdn: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=1200&q=80&auto=format&fit=crop',
    heroImageAlt: 'Petronas Twin Towers at night, Kuala Lumpur',
    heroImageCredit: 'Unsplash'
  },
  stays: [
    {
      id: 'mov', name: 'MOV Hotel Kuala Lumpur', zhName: 'MOV Hotel 吉隆坡',
      dates: 'Oct 2 – 5', nights: 3, status: 'confirmed',
      address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
      lat: 3.1462, lng: 101.7097,
      checkIn: '15:00', checkOut: '12:00',
      image: 'img/hotel.webp',
      imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
      imageAlt: 'Boutique hotel room interior', imageCredit: 'Unsplash',
      nearestMRT: 'Bukit Bintang MRT / Monorail Station',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=MOV+Hotel+Kuala+Lumpur'
    },
    {
      id: 'pd', name: 'Port Dickson Beach Hotel', zhName: '波德申海滩酒店',
      dates: 'Oct 5 – 6', nights: 1, status: 'tentative',
      address: 'Port Dickson, Negeri Sembilan（酒店待最终确认）',
      lat: 2.5167, lng: 101.8000,
      checkIn: '15:00', checkOut: '11:00',
      candidates: ['Avillion Port Dickson', 'Pacific Regency Beach Resort', 'Thistle Port Dickson'],
      image: 'img/d4-4.webp',
      imageCdn: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
      imageAlt: 'Beach resort in Port Dickson', imageCredit: 'Unsplash',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Port+Dickson+Beach'
    }
  ],
  flights: {
    outbound: { from: 'HGH', to: 'KUL', date: '2026-10-02', dep: '08:55', arr: '14:20', note: '已购票' },
    inbound: { from: 'KUL', to: 'HGH', date: '2026-10-06', dep: '15:20', arr: '20:30', note: '已购票' }
  },
  days: [
    {
      id: 1, num: '02', date: '02 October', weekday: 'Friday',
      title: '抵达吉隆坡', theme: '抵达 × 入住 × 夜市',
      summary: { spots: 5, walks: '约 2 km', grabs: 1, budget: 'RM 80–120 / 人' },
      transport: {
        mode: '🚄 KLIA Ekspres + Grab', tag: '机场交通',
        from: { code: 'KUL T1', sub: '吉隆坡机场第一航站楼' },
        mid: { icon: '🚄', dur: '约 33 分钟' },
        to: { code: 'KL Sentral', sub: '换乘 Grab 进市区' },
        note: '机场进城建议 KLIA Ekspres 至 KL Sentral（约 33 分钟，约 15–20 分钟一班，以现场为准），再换 Grab 前往酒店。'
      },
      spots: [
        { time: '08:55', type: 'transit', emoji: '🛫', zh: '杭州萧山机场 HGH', en: 'Hangzhou Xiaoshan Airport',
          note: '起飞', lat: 30.2294, lng: 120.4343,
          address: '杭州萧山国际机场', duration: '—', openingHours: '—', ticket: '已购票',
          image: 'img/d1-1.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/KLIA_Main_Terminal_Building_2023.jpg/640px-KLIA_Main_Terminal_Building_2023.jpg',
          imageAlt: 'Airport departure', imageCredit: 'Wikimedia Commons',
          tips: ['提前值机','国际航班建议提前 2 小时到达'],
          next: { mode: 'transit', text: '飞行至吉隆坡（约 5.5 小时）' }
        },
        { time: '14:20', type: 'transit', emoji: '🛬', zh: '吉隆坡国际机场 T1', en: 'Kuala Lumpur International Airport T1',
          note: '抵达，入境 + 提取行李', lat: 2.7456, lng: 101.7099,
          address: '64000 Sepang, Selangor',
          duration: '约 1–1.5 小时（入境+取行李）', openingHours: '24 小时', ticket: '无',
          image: 'img/d1-1.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/KLIA_Main_Terminal_Building_2023.jpg/640px-KLIA_Main_Terminal_Building_2023.jpg',
          imageAlt: 'KLIA Main Terminal Building', imageCredit: 'Wikimedia Commons',
          tips: ['提前填好马来西亚入境卡（MDAC）','提取行李后跟随 signs 到 KLIA Ekspres'],
          next: { mode: 'transit', text: 'KLIA Ekspres 至 KL Sentral（约 33 分钟），再换 Grab 至酒店' }
        },
        { time: '16:45', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '入住及放行李', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '约 30 分钟', openingHours: '入住 15:00 / 退房 12:00', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Boutique hotel room interior', imageCredit: 'Unsplash',
          tips: ['若房间未准备好可先寄存行李','酒店位于 Bukit Bintang 核心区，步行可达商圈'],
          next: { mode: 'walk', text: '步行至武吉免登商圈（约 5 分钟）' }
        },
        { time: '18:15', type: 'shopping', emoji: '🛍️', zh: 'Pavilion 吉隆坡', en: 'Pavilion Kuala Lumpur',
          note: '商场及晚餐', lat: 3.1486, lng: 101.7136,
          address: '168, Jalan Bukit Bintang, 55100 Kuala Lumpur',
          duration: '约 1–1.5 小时', openingHours: '10:00 – 22:00', ticket: '无',
          image: 'img/d1-4.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pavilion_KL_%282022%29.jpg/640px-Pavilion_KL_%282022%29.jpg',
          imageAlt: 'Pavilion Kuala Lumpur exterior', imageCredit: 'Wikimedia Commons',
          tips: ['KL 最高端商场之一','地下美食街 Food Republic 选择丰富'],
          next: { mode: 'walk', text: '步行至阿罗街（约 10 分钟）' }
        },
        { time: '19:20', type: 'food', emoji: '🍜', zh: '阿罗街', en: 'Jalan Alor Food Street',
          note: '夜市晚餐', lat: 3.1434, lng: 101.7080,
          address: 'Jalan Alor, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '约 1.5–2 小时', openingHours: '约 17:00 – 次日 01:00', ticket: '无',
          image: 'img/d1-5.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Jalan_Alor_%282022%29.jpg/640px-Jalan_Alor_%282022%29.jpg',
          imageAlt: 'Jalan Alor street food stalls at night', imageCredit: 'Wikimedia Commons',
          tips: ['现金为主（多数摊位不收卡）','推荐 Wong Ah Wah 炭烤鸡翅、Satay、Char Kway Teow','周末和节假日非常拥挤'],
          next: { mode: 'walk', text: '步行返回酒店（约 8 分钟）' }
        }
      ],
      restaurants: [
        { meal: 'dinner', time: '约 19:20',
          name: 'Jalan Alor 街头美食', zhName: '阿罗街夜市',
          cuisine: '马来西亚中式街头美食', tags: ['Chinese', 'Street Food', 'Cash Only'],
          recommendedDishes: ['Wong Ah Wah 炭烤鸡翅','Satay 沙爹','Char Kway Teow 炒粿条','Cendol 煎蕊'],
          pricePerPerson: 'RM 25–45', openingHours: '约 17:00 – 01:00',
          distanceFromPrev: '步行 10 分钟（从 Pavilion）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jalan+Alor+Kuala+Lumpur',
          backup: { name: 'Lot 10 Hutong Food Court', zhName: '十号胡同', note: '室内空调，雨天备用，同区域' }
        }
      ]
    },
    {
      id: 2, num: '03', date: '03 October', weekday: 'Saturday',
      title: '吉隆坡市区', theme: '历史街区 × 城市地标',
      summary: { spots: 7, walks: '约 4 km', grabs: 2, budget: 'RM 60–100 / 人' },
      transport: {
        mode: '🚇 MRT / LRT + 步行', tag: '市区移动',
        from: { code: '历史街区', sub: '茨厂街一带' },
        mid: { icon: '🚇', dur: '视路段' },
        to: { code: 'KLCC', sub: '双子塔一带' },
        note: '市区以步行 + MRT/LRT 为主。国家博物馆 → 茨厂街可乘 Grab 或公共交通；独立广场 → KLCC 建议 MRT/LRT 或 Grab，不安排驾车。'
      },
      spots: [
        { time: '08:15', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '早餐后出发', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '—', openingHours: '—', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Boutique hotel room interior', imageCredit: 'Unsplash',
          tips: [],
          next: { mode: 'grab', text: '建议 Grab 前往国家博物馆（约 10 分钟）' }
        },
        { time: '09:30', type: 'attraction', emoji: '🏛️', zh: '国家博物馆', en: 'National Museum of Malaysia (Muzium Negara)',
          note: '马来西亚历史概览', lat: 3.1383, lng: 101.6865,
          address: 'Jalan Damansara, Perdana Botanical Gardens, 50566 Kuala Lumpur',
          duration: '约 1.5–2 小时', openingHours: '09:00 – 18:00', ticket: 'RM 5（马来西亚公民 RM 2）',
          image: 'img/d2-2.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/National_Museum_%28Muzium_Negara%29_2023.jpg/640px-National_Museum_%28Muzium_Negara%29_2023.jpg',
          imageAlt: 'National Museum building with traditional Malay architecture', imageCredit: 'Wikimedia Commons',
          tips: ['主楼有 4 个展厅','建筑本身就是亮点（传统马来风格）'],
          next: { mode: 'grab', text: '建议 Grab 或 MRT 至茨厂街（约 10–15 分钟）' }
        },
        { time: '12:50', type: 'attraction', emoji: '🏮', zh: '茨厂街', en: 'Petaling Street / Chinatown',
          note: '唐人街街区', lat: 3.1440, lng: 101.6970,
          address: 'Jalan Petaling, City Centre, 50000 Kuala Lumpur',
          duration: '约 35 分钟', openingHours: '约 08:00 – 22:00', ticket: '无',
          image: 'img/d2-3.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Petaling_Street_%282022%29.jpg/640px-Petaling_Street_%282022%29.jpg',
          imageAlt: 'Petaling Street arch gate and market', imageCredit: 'Wikimedia Commons',
          tips: ['著名牌坊和遮阳棚','假货市场+美食并存','附近有关帝庙和马里安曼庙'],
          next: { mode: 'walk', text: '步行（约 3 分钟）' }
        },
        { time: '13:30', type: 'attraction', emoji: '🏮', zh: '鬼仔巷', en: 'Kwai Chai Hong',
          note: '壁画与老街空间', lat: 3.1446, lng: 101.6982,
          address: 'Lorong Panggung, City Centre, 50000 Kuala Lumpur',
          duration: '约 30 分钟', openingHours: '全天', ticket: '无',
          image: 'img/d2-4.webp', imageCdn: 'https://images.unsplash.com/photo-1580910533731-f52e3f382324?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Colorful street art in Kuala Lumpur alley', imageCredit: 'Unsplash',
          tips: ['茨厂街旁的小巷','多幅创意壁画适合拍照'],
          next: { mode: 'walk', text: '步行至中央艺术坊（约 5 分钟）' }
        },
        { time: '14:05', type: 'attraction', emoji: '🎨', zh: '中央艺术坊', en: 'Central Market Kuala Lumpur',
          note: '工艺品与本地文化', lat: 3.1468, lng: 101.6957,
          address: 'Jalan Hang Kasturi, City Centre, 50050 Kuala Lumpur',
          duration: '约 45 分钟', openingHours: '10:00 – 21:30', ticket: '无',
          image: 'img/d2-5.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Central_Market_KL_%282022%29.jpg/640px-Central_Market_KL_%282022%29.jpg',
          imageAlt: 'Central Market KL art deco building', imageCredit: 'Wikimedia Commons',
          tips: ['二楼 Precious Old China 是知名娘惹餐厅','适合买手信'],
          next: { mode: 'walk', text: '步行至独立广场（约 8 分钟）' }
        },
        { time: '15:00', type: 'attraction', emoji: '🏛️', zh: '独立广场', en: 'Merdeka Square',
          note: '历史地标（沿途可见苏丹阿都沙末大厦）', lat: 3.1478, lng: 101.6932,
          address: 'Jalan Raja, City Centre, 50050 Kuala Lumpur',
          duration: '约 40 分钟', openingHours: '全天', ticket: '无',
          image: 'img/d2-6.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Merdeka_Square_%282022%29.jpg/640px-Merdeka_Square_%282022%29.jpg',
          imageAlt: 'Merdeka Square with flagpole and Sultan Abdul Samad Building', imageCredit: 'Wikimedia Commons',
          tips: ['世界最高旗杆（95 米）','对面是苏丹阿都沙末大厦（不必单独进入）','附近是城市画廊（可选）'],
          next: { mode: 'grab', text: 'Grab 返回 MOV 休息（约 15 分钟）' }
        },
        { time: '16:05', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '酒店休息 / 洗澡 / 换衣', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '约 1 小时', openingHours: '—', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Hotel room for afternoon rest', imageCredit: 'Unsplash',
          tips: ['避开正午高温','休整后再出发'],
          next: { mode: 'grab', text: 'Grab 前往 KLCC（约 15 分钟）' }
        },
        { time: '18:00', type: 'attraction', emoji: '🌉', zh: '双子塔 KLCC', en: 'Petronas Twin Towers',
          note: '城市地标收尾', lat: 3.1580, lng: 101.7116,
          address: 'Kuala Lumpur City Centre, 50088 Kuala Lumpur',
          duration: '约 1–2 小时', openingHours: '商场 10:00 – 22:00 / 空中走廊周二至日 09:00 – 17:00（周一关闭）', ticket: '空中走廊需预约购票',
          image: 'img/d2-7.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Petronas_Twin_Towers.jpg/640px-Petronas_Twin_Towers.jpg',
          imageAlt: 'Petronas Twin Towers reflecting in pool', imageCredit: 'Wikimedia Commons',
          tips: ['夜景最佳拍摄点在 Suria KLCC 门口喷泉','KLCC Park 适合散步','空中走廊门票建议提前官网预约'],
          next: { mode: 'walk', text: '步行至 KLCC Park' }
        }
      ],
      restaurants: [
        { meal: 'breakfast', time: '约 08:15',
          name: 'Ali, Muthu & Ah Hock', zhName: '阿里姆图阿霍',
          cuisine: '马来西亚 Kopitiam', tags: ['Halal-friendly', 'Local'],
          recommendedDishes: ['Nasi Lemak Ayam 椰浆饭配炸鸡','Teh Tarik 拉茶'],
          pricePerPerson: 'RM 12–18', openingHours: '08:00 – 17:00',
          distanceFromPrev: '约 200m（从 Pasar Seni MRT / 中央市场）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ali+Muthu+Ah+Hock+Kuala+Lumpur',
          backup: { name: 'Central Market 一楼 Food Court', zhName: '中央市场美食广场', note: '多种选择，空调' }
        },
        { meal: 'lunch', time: '约 12:00',
          name: 'Hon Kee Porridge / Koon Kee Wantan Mee', zhName: '汉记粥品 / 坤记云吞面',
          cuisine: '马来西亚中式', tags: ['Chinese', 'Pork'],
          recommendedDishes: ['Hon Kee 生鱼粥','Koon Kee 云吞面配叉烧'],
          pricePerPerson: 'RM 8–15', openingHours: 'Hon Kee 05:00–14:30 / Koon Kee 09:30–14:30',
          distanceFromPrev: '步行范围内（茨厂街/鬼仔巷附近）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hon+Kee+Porridge+Kuala+Lumpur',
          backup: { name: 'Madras Lane Curry Laksa', zhName: '马德里巷咖喱叻沙', note: '咖喱/亚参叻沙，约 RM 7–10' }
        },
        { meal: 'dinner', time: '约 19:45',
          name: 'Suria KLCC / Jalan Alor', zhName: 'Suria KLCC 商场 / 阿罗街',
          cuisine: '商场美食广场 / 街头美食', tags: ['Mixed'],
          recommendedDishes: ['商场：各式档口','阿罗街：Satay、烤鸡翅、Cendol'],
          pricePerPerson: 'RM 25–50', openingHours: '商场 10:00–22:00 / 阿罗街 17:00–01:00',
          distanceFromPrev: 'KLCC 或返回 Bukit Bintang',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Suria+KLCC+Food+Court',
          backup: { name: 'Pavilion KL Food Republic', zhName: 'Pavilion 大食代', note: '室内空调，雨天备用' }
        }
      ]
    },
    {
      id: 3, num: '04', date: '04 October', weekday: 'Sunday',
      title: '马六甲', theme: '马六甲文化一日游',
      summary: { spots: 7, walks: '约 3 km', grabs: 2, budget: 'RM 100–150 / 人（含巴士）', endTime: '约 00:10' },
      transport: {
        mode: '🚌 长途巴士', tag: '跨城交通',
        from: { code: 'TBS', sub: '吉隆坡南湖镇车站' },
        mid: { icon: '🚌', dur: '约 2–2.5 小时' },
        to: { code: 'Melaka Sentral', sub: '马六甲中央车站' },
        note: '吉隆坡—马六甲仅以长途巴士接驳（不驾车、不 Grab）。TBS 与 Melaka Sentral 为交通节点，不入正式行程；班次以现场为准。市区景点间步行串联。'
      },
      spots: [
        { time: '07:30', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '早餐后出发，行李寄存前台', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '—', openingHours: '—', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Boutique hotel room interior', imageCredit: 'Unsplash',
          tips: ['行李寄存前台','轻装前往马六甲'],
          next: { mode: 'transit', text: 'Grab 至 TBS → 长途巴士（约 2–2.5 小时）→ Melaka Sentral → Grab 进古城' }
        },
        { time: '11:40', type: 'attraction', emoji: '🏛️', zh: '马六甲红屋', en: 'Dutch Square / The Stadthuys',
          note: '荷兰广场历史核心', lat: 2.1940, lng: 102.2490,
          address: 'Jalan Kota, Bandar Hilir, 75000 Malacca',
          duration: '约 40 分钟', openingHours: '约 09:00 – 17:30', ticket: '广场免费， Stadthuys 博物馆约 RM 10',
          image: 'img/d3-2.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Stadthuys_Melaka.jpg/640px-Stadthuys_Melaka.jpg',
          imageAlt: 'Red Stadthuys building in Dutch Square Melaka', imageCredit: 'Wikimedia Commons',
          tips: ['标志性红色建筑','广场中央有维多利亚女王喷泉','旁边是基督教堂'],
          next: { mode: 'walk', text: '步行（约 3 分钟）' }
        },
        { time: '13:25', type: 'attraction', emoji: '🏠', zh: '峇峇娘惹祖屋', en: 'Baba & Nyonya Heritage Museum',
          note: '土生华人宅邸博物馆（可选/推荐）', lat: 2.1956, lng: 102.2462,
          address: '48-50, Jalan Tun Tan Cheng Lock, 75200 Malacca',
          duration: '约 55 分钟', openingHours: '10:00 – 16:15（周一关闭）', ticket: '约 RM 18',
          image: 'img/d3-3.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Baba_Nyonya_Heritage_Museum.jpg/640px-Baba_Nyonya_Heritage_Museum.jpg',
          imageAlt: 'Baba Nyonya Heritage Museum interior courtyard', imageCredit: 'Wikimedia Commons',
          tips: ['需跟随导览（有指定时间）','内部禁止拍照','太累可删除'],
          next: { mode: 'walk', text: '步行至圣保罗山（约 8 分钟）' }
        },
        { time: '14:25', type: 'attraction', emoji: '⛪', zh: '圣保罗山', en: "St. Paul's Hill Melaka",
          note: '俯瞰古城（山下可顺路看 A Famosa 遗门）', lat: 2.1935, lng: 102.2495,
          address: 'Jalan Kota, Bandar Hilir, 75000 Malacca',
          duration: '约 50 分钟', openingHours: '全天', ticket: '无',
          image: 'img/d3-4.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/St._Paul%27s_Church_Melaka.jpg/640px-St._Paul%27s_Church_Melaka.jpg',
          imageAlt: 'St. Paul Church ruins on hilltop overlooking Malacca', imageCredit: 'Wikimedia Commons',
          tips: ['山顶可俯瞰马六甲全城','下山时顺路看 A Famosa 古城门遗骸（不单独编号）'],
          next: { mode: 'walk', text: '步行至 Cendol 甜品店' }
        },
        { time: '15:50', type: 'attraction', emoji: '🛕', zh: '青云亭', en: 'Cheng Hoon Teng Temple',
          note: '马来西亚最古老华人寺庙', lat: 2.1955, lng: 102.2464,
          address: '25, Jalan Tokong, 75200 Malacca',
          duration: '约 25 分钟', openingHours: '约 07:00 – 19:00', ticket: '无',
          image: 'img/d3-5.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cheng_Hoon_Teng_Temple.jpg/640px-Cheng_Hoon_Teng_Temple.jpg',
          imageAlt: 'Cheng Hoon Teng Temple traditional Chinese architecture', imageCredit: 'Wikimedia Commons',
          tips: ['马来西亚最古老华人寺庙','建筑精美，可静静参观'],
          next: { mode: 'walk', text: '步行至游船码头（约 5 分钟）' }
        },
        { time: '16:25', type: 'attraction', emoji: '🛶', zh: '马六甲河游船', en: 'Melaka River Cruise',
          note: '傍晚场次光线较好', lat: 2.1944, lng: 102.2468,
          address: 'Jalan Persisiran Bunga Raya, 75100 Malacca',
          duration: '约 50 分钟', openingHours: '约 09:00 – 22:30', ticket: '约 RM 30（成人）',
          image: 'img/d3-6.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Melaka_River_Cruise.jpg/640px-Melaka_River_Cruise.jpg',
          imageAlt: 'Colorful buildings along Melaka River with cruise boat', imageCredit: 'Wikimedia Commons',
          tips: ['傍晚 17:00–18:30 光线最佳','沿河可看到彩色壁画建筑'],
          next: { mode: 'walk', text: '步行过桥即鸡场街（约 3 分钟）' }
        },
        { time: '18:00', type: 'food', emoji: '🏮', zh: '鸡场街夜市', en: 'Jonker Street Night Market',
          note: '老街夜市（仅周末开放，今晚是周日）', lat: 2.1967, lng: 102.2460,
          address: 'Jalan Hang Jebat, 75200 Malacca',
          duration: '约 2 小时 10 分钟', openingHours: '周五至周日 约 18:00 – 00:00', ticket: '无',
          image: 'img/d3-7.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Jonker_Street_Night_Market.jpg/640px-Jonker_Street_Night_Market.jpg',
          imageAlt: 'Jonker Street crowded night market with food stalls', imageCredit: 'Wikimedia Commons',
          tips: ['仅周五至周日晚上开放','推荐 Jonker 88 叻沙、Cendol、Popiah','今晚是行程最晚一天'],
          next: { mode: 'transit', text: '夜市后 Grab 至 Melaka Sentral → 长途巴士返吉隆坡（约 21:00）' }
        }
      ],
      restaurants: [
        { meal: 'breakfast', time: '约 07:00',
          name: '酒店附近轻食 / TBS 车站', zhName: '酒店或车站简餐',
          cuisine: '轻食', tags: ['Quick'],
          recommendedDishes: ['酒店早餐或附近 Kopitiam'],
          pricePerPerson: 'RM 8–15', openingHours: '视地点',
          distanceFromPrev: '酒店内或附近',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=breakfast+near+Bukit+Bintang',
          backup: { name: 'TBS 车站内便利店', zhName: 'TBS 便利店', note: '上车前简单解决' }
        },
        { meal: 'lunch', time: '约 12:25',
          name: 'Jonker 88', zhName: '大宝小食',
          cuisine: 'Nyonya / Peranakan', tags: ['Halal-friendly', 'Queue Expected'],
          recommendedDishes: ['Nyonya Asam Laksa 亚参叻沙','Baba Laksa  Baba 叻沙','Cendol Gula Melaka 煎蕊椰糖'],
          pricePerPerson: 'RM 12–20', openingHours: '约 10:00 – 19:30',
          distanceFromPrev: '步行 3 分钟（从红屋）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jonker+88+Melaka',
          backup: { name: 'Peranakan Place', zhName: 'Peranakan Place', note: '空调座位，同街，约 RM 20–40/人' }
        },
        { meal: 'snack', time: '约 15:20',
          name: 'Cendol 甜品店', zhName: '煎蕊甜品',
          cuisine: '甜品', tags: ['Dessert', 'Local'],
          recommendedDishes: ['Cendol Gula Melaka','Ais Kacang'],
          pricePerPerson: 'RM 5–8', openingHours: '视店铺',
          distanceFromPrev: '圣保罗山附近',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=cendol+melaka',
          backup: { name: '任意 Cendol 摊位', zhName: '任意煎蕊摊', note: '街头随处可见' }
        },
        { meal: 'dinner', time: '约 18:00',
          name: '鸡场街夜市', zhName: '鸡场街夜市',
          cuisine: '街头美食', tags: ['Street Food', 'Weekend Only'],
          recommendedDishes: ['Popiah 薄饼','Satay 沙爹','Cendol 煎蕊','Nyonya Kuih 娘惹糕'],
          pricePerPerson: 'RM 15–30', openingHours: '周五至周日 约 18:00 – 00:00',
          distanceFromPrev: '步行过桥（从游船码头）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jonker+Street+Night+Market+Melaka',
          backup: { name: 'Jonker Kitchen', zhName: 'Jonker Kitchen', note: '空调座位有限，约 RM 20–40/人' }
        }
      ]
    },
    {
      id: 4, num: '05', date: '05 October', weekday: 'Monday',
      title: '黑风洞 × 波德申', theme: '上午文化景点 × 下午海边度假',
      summary: { spots: 5, walks: '约 2 km', grabs: 3, budget: 'RM 180–260 / 人' },
      transport: {
        mode: '🚗 Grab（叫车）', tag: '往返黑风洞 + 跨城',
        from: { code: 'MOV Hotel', sub: '武吉免登' },
        mid: { icon: '🚗', dur: '黑风洞约 20–30 分钟 / 波德申约 1.5–2 小时' },
        to: { code: 'Port Dickson', sub: '波德申海边' },
        note: '黑风洞往返建议 Grab。MOV → Port Dickson 建议 Grab/Private Transfer（约 1.5–2 小时，预计 RM 150–250），不安排 MRT+KTM+Bus。'
      },
      spots: [
        { time: '08:30', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '早餐后出发', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '—', openingHours: '—', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Boutique hotel room interior', imageCredit: 'Unsplash',
          tips: [],
          next: { mode: 'grab', text: 'Grab 前往黑风洞（约 20–30 分钟）' }
        },
        { time: '09:30', type: 'attraction', emoji: '🛕', zh: '黑风洞', en: 'Batu Caves',
          note: '彩虹阶梯 + 印度教圣地', lat: 3.2374, lng: 101.6839,
          address: 'Gombak, 68100 Batu Caves, Selangor',
          duration: '约 1.5 小时', openingHours: '约 06:00 – 21:00', ticket: '无（ donations 自愿）',
          image: 'img/d4-2.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Batu_Caves_Murugan.jpg/640px-Batu_Caves_Murugan.jpg',
          imageAlt: 'Batu Caves colorful staircase and giant Murugan statue', imageCredit: 'Wikimedia Commons',
          tips: ['需攀登 272 级彩虹阶梯','猴子会抢食物，不要手拿塑料袋','建议穿长裤/长裙（宗教场所）','洞内需脱鞋','下雨台阶滑，注意安全'],
          next: { mode: 'grab', text: 'Grab 返回 MOV（约 20–30 分钟）' }
        },
        { time: '11:35', type: 'hotel', emoji: '🏨', zh: 'MOV Hotel', en: 'MOV Hotel Kuala Lumpur',
          note: '整理行李 + 退房（12:00 前）', lat: 3.1462, lng: 101.7097,
          address: 'Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur',
          duration: '约 25 分钟', openingHours: '退房 12:00', ticket: '无',
          image: 'img/hotel.webp', imageCdn: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Hotel room check out', imageCredit: 'Unsplash',
          tips: ['确认无遗漏物品','行李随身'],
          next: { mode: 'walk', text: '步行至 Bukit Bintang 附近午餐' }
        },
        { time: '13:15', type: 'transit', emoji: '🚗', zh: '前往波德申', en: 'To Port Dickson',
          note: 'Grab / Private Transfer', lat: 2.5167, lng: 101.8000,
          address: 'Port Dickson, Negeri Sembilan',
          duration: '约 1.5–2 小时', openingHours: '—', ticket: '预计 RM 150–250（Grab）',
          image: 'img/d4-4.webp', imageCdn: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Beach road to Port Dickson', imageCredit: 'Unsplash',
          tips: ['建议提前叫车','备晕车药（如需）','途中可休息'],
          next: { mode: 'walk', text: '抵达酒店 Check-in' }
        },
        { time: '15:00', type: 'hotel', emoji: '🏨', zh: '波德申酒店', en: 'Port Dickson Beach Hotel',
          note: 'Check-in / 换衣 / 休息', lat: 2.5167, lng: 101.8000,
          address: 'Port Dickson, Negeri Sembilan（酒店待最终确认）',
          duration: '约 40 分钟', openingHours: '入住 15:00 / 退房 11:00', ticket: '无',
          image: 'img/d4-4.webp', imageCdn: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Beach hotel room', imageCredit: 'Unsplash',
          tips: ['酒店待确认（候选：Avillion / Pacific Regency / Thistle）','换泳装/轻便衣物'],
          next: { mode: 'walk', text: '步行至 Saujana Beach（约 10–15 分钟）' }
        },
        { time: '15:45', type: 'attraction', emoji: '🏖️', zh: 'Saujana Beach', en: 'Saujana Beach',
          note: '海边休息 · 日落', lat: 2.5200, lng: 101.7950,
          address: 'Saujana Beach, Port Dickson, Negeri Sembilan',
          duration: '约 1.5–2 小时', openingHours: '全天', ticket: '无',
          image: 'img/d4-5.webp', imageCdn: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Saujana Beach sunset in Port Dickson', imageCredit: 'Unsplash',
          tips: ['17:30–19:10 日落最佳','带防晒霜和毛巾','海边散步放松'],
          next: { mode: 'walk', text: '步行至海鲜餐厅（约 10 分钟）' }
        },
        { time: '19:20', type: 'food', emoji: '🦀', zh: '海鲜晚餐', en: 'Port Dickson Seafood Dinner',
          note: '海边海鲜大餐', lat: 2.5180, lng: 101.7980,
          address: 'Port Dickson, Negeri Sembilan（餐厅待确认）',
          duration: '约 1 小时 20 分钟', openingHours: '约 17:00 – 22:00', ticket: '约 RM 40–80 / 人',
          image: 'img/d4-5.webp', imageCdn: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Seafood dinner by the beach', imageCredit: 'Unsplash',
          tips: ['推荐奶油虾、清蒸鱼、炒蟹','餐厅待最终确认'],
          next: { mode: 'walk', text: '海边散步后返回酒店' }
        }
      ],
      restaurants: [
        { meal: 'breakfast', time: '约 08:00',
          name: '酒店附近', zhName: '酒店附近',
          cuisine: '轻食', tags: ['Quick'],
          recommendedDishes: ['酒店早餐或附近 Kopitiam'],
          pricePerPerson: 'RM 8–15', openingHours: '视地点',
          distanceFromPrev: '酒店内或附近',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=breakfast+near+Bukit+Bintang',
          backup: { name: '便利店', zhName: '便利店', note: '7-Eleven / FamilyMart' }
        },
        { meal: 'lunch', time: '约 12:00',
          name: 'Bukit Bintang 附近', zhName: '肉骨茶 / 海南鸡饭',
          cuisine: '马来西亚中式', tags: ['Chinese', 'Local'],
          recommendedDishes: ['Bak Kut Teh 肉骨茶','Hainanese Chicken Rice 海南鸡饭'],
          pricePerPerson: 'RM 15–25', openingHours: '约 10:00 – 22:00',
          distanceFromPrev: 'MOV 酒店附近（Bukit Bintang）',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bak+Kut+Teh+Bukit+Bintang',
          backup: { name: '商场 Food Court', zhName: '商场美食广场', note: '多种选择，空调' }
        },
        { meal: 'dinner', time: '约 19:20',
          name: 'Port Dickson Seafood', zhName: '波德申海鲜晚餐',
          cuisine: '海鲜', tags: ['Seafood', 'Chinese Style'],
          recommendedDishes: ['奶油虾','清蒸鱼','炒蟹','炒花甲'],
          pricePerPerson: 'RM 40–80', openingHours: '约 17:00 – 22:00',
          distanceFromPrev: 'Saujana Beach 附近',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=seafood+restaurant+Port+Dickson',
          backup: { name: '酒店餐厅', zhName: '酒店餐厅', note: '雨天备用' }
        }
      ]
    },
    {
      id: 5, num: '06', date: '06 October', weekday: 'Tuesday',
      title: '返程', theme: '海边 × 机场',
      summary: { spots: 3, walks: '约 1 km', grabs: 1, budget: 'RM 30–50 / 人' },
      transport: {
        mode: '🚗 Grab / Hotel Transfer', tag: '机场交通',
        from: { code: 'Port Dickson', sub: '波德申' },
        mid: { icon: '🚗', dur: '约 50–80 分钟' },
        to: { code: 'KUL T1', sub: '吉隆坡机场第一航站楼' },
        note: 'Port Dickson → KUL T1 建议 Grab 或酒店接送（约 50–80 分钟，预算 60–80 分钟缓冲）。不考虑公交。'
      },
      spots: [
        { time: '08:00', type: 'hotel', emoji: '🏨', zh: '波德申酒店', en: 'Port Dickson Beach Hotel',
          note: '早餐 / 海边散步 / 整理', lat: 2.5167, lng: 101.8000,
          address: 'Port Dickson, Negeri Sembilan',
          duration: '约 2 小时', openingHours: '退房 11:00', ticket: '无',
          image: 'img/d4-4.webp', imageCdn: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
          imageAlt: 'Beach hotel morning', imageCredit: 'Unsplash',
          tips: ['09:00–10:00 海边散步或 Pool','10:00–10:30 洗澡','10:30–11:00 整理行李退房'],
          next: { mode: 'grab', text: 'Grab / 酒店接送至 KUL T1（约 50–80 分钟）' }
        },
        { time: '11:00', type: 'transit', emoji: '🚗', zh: '前往机场', en: 'To KUL T1',
          note: 'Grab / Hotel Transfer', lat: 2.7456, lng: 101.7099,
          address: '64000 Sepang, Selangor',
          duration: '约 50–80 分钟', openingHours: '—', ticket: '预计 RM 80–150',
          image: 'img/d5-2.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/KLIA_Main_Terminal_Building_2023.jpg/640px-KLIA_Main_Terminal_Building_2023.jpg',
          imageAlt: 'Road to airport', imageCredit: 'Wikimedia Commons',
          tips: ['预留充足时间','建议 11:00 出发，12:00–12:20 到达'],
          next: { mode: 'transit', text: '值机 / 安检 / 出境' }
        },
        { time: '12:20', type: 'transit', emoji: '🛫', zh: '吉隆坡国际机场 T1', en: 'Kuala Lumpur International Airport T1',
          note: '办理登机，返程', lat: 2.7456, lng: 101.7099,
          address: '64000 Sepang, Selangor',
          duration: '约 3 小时（值机+安检+出境+购物）', openingHours: '24 小时', ticket: '无',
          image: 'img/d5-3.webp', imageCdn: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/KLIA_Main_Terminal_Building_2023.jpg/640px-KLIA_Main_Terminal_Building_2023.jpg',
          imageAlt: 'KLIA Main Terminal Building departure hall', imageCredit: 'Wikimedia Commons',
          tips: ['国际航班建议提前 3 小时到达','15:20 起飞，20:30 抵达杭州'],
          next: { mode: 'none', text: '' }
        }
      ],
      restaurants: [
        { meal: 'breakfast', time: '约 08:00',
          name: '酒店餐厅 / 附近', zhName: '酒店早餐或附近',
          cuisine: '轻食', tags: ['Quick'],
          recommendedDishes: ['酒店早餐或附近 Kopitiam'],
          pricePerPerson: 'RM 8–15', openingHours: '视地点',
          distanceFromPrev: '酒店内或附近',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=breakfast+Port+Dickson',
          backup: { name: '便利店', zhName: '便利店', note: '7-Eleven / FamilyMart' }
        },
        { meal: 'lunch', time: '约 12:00',
          name: 'KUL T1 机场', zhName: '吉隆坡机场 T1',
          cuisine: '机场美食', tags: ['Mixed'],
          recommendedDishes: ['机场 Food Court 各式档口','Old Town White Coffee 白咖啡'],
          pricePerPerson: 'RM 20–40', openingHours: '约 06:00 – 23:00',
          distanceFromPrev: '机场内',
          googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=food+court+KLIA+Terminal+1',
          backup: { name: '机场便利店', zhName: '机场便利店', note: '7-Eleven / Starbucks' }
        }
      ]
    }
  ],
  transitNodes: [
    { name: 'TBS 南湖镇车站', lat: 3.0750, lng: 101.7110, day: 3, type: 'transit' },
    { name: 'Melaka Sentral 马六甲中央车站', lat: 2.2207, lng: 102.2507, day: 3, type: 'transit' }
  ]
};
